# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Music Recommendation
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://krchatbot.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: History
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: dinky_apple@naver.com
      link: mailto:dinky_apple@naver.com
    - name: KakaoTalk
      value: dinky24
      link: "#"
  follow:
    - name: Twitter
      link: 
      username: "@YourTwitterUsername"
    - name: Facebook
      link: 
    - name: LinkedIn
      link: 
    - name: GitHub
      link: https://github.com/krChatBot/client
    - name: Weibo
      link: 
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
